### PR TITLE
 Use custom-available-themes

### PR DESCRIPTION
**Pull request by hexmode**
This will make all the themes in the custom-theme-load-path (including those in, say, data-directory/themes) available to be used instead of only those in load-path.

also, a couple of other changes to address flycheck warnings.

### CODE REVIEW

**Comment by jasonm23** [comment]
it would probably be a good time to also make the return value of `remember-theme-read` an interned symbol, instead of doing it on the let of `remember theme load`.  Up to you though.

Please bump the version to the current UTC in the same format.  Update the Changelog - and you can add your name to authors.  In the package comment.

**Comment by jasonm23** [comment]
Oh and please forgive me, I forgot to thank you! (I do this a lot!)

Thank you!

**Comment by hexmode** [comment]
Could this be merged now?

**Comment by jasonm23** [comment]
Definitely.  I don't get pinged when you add commits to the pull request BTW, only comments.

**Pull request merged**
